### ISSUE TITLE
keep clean the Location + Gridsquare Fields during /p, /m, /mm activities

### ISSUE THREAD

**Issue by dg2ron** [wavelog/wavelog#1189] opened 2024-11-12 10:14 UTC
Is it possible to keep the Location and Gridsquare fields free during /p, /m or /mm? 
You are never at the specified location when you are /p, /m or /mm

I have noticed that these two fields are often filled in. Whether this data comes from QRZ or from past QSOs remains to be determined. In my opinion, these fields should be left blank and filled in optionally.

**Comment by HB9HIL** [comment] 2024-11-12 10:17
Hello @dg2ron 

Are you talking about the QSO logging or the station setup?

Can you precise your question?

**Comment by dg2ron** [comment] 2024-11-12 11:20
QSO logging

![image](https://github.com/user-attachments/assets/38f7ba53-43f7-484f-9ac7-153a773f11be)
...
![image](https://github.com/user-attachments/assets/7ab4dcd0-8d1a-4471-9984-696ee29884a8)


I think he is pulling the "wrong location" from a past QSO.

**Comment by HB9HIL** [comment] 2024-11-12 11:35
Please tell me:

- Which Version of Wavelog are you running? This issue was fixed in #452  and released in Version `1.7`
- Which callbook is configured? `qrz` or `hamqth`

**Comment by int2001** [comment] 2024-11-12 11:37
@HB9HIL he uses latest dev. qrz is configured.

**Comment by HB9HIL** [comment] 2024-11-12 11:41
@dg2ron @int2001 

I was able to reproduce this issue. 

@dg2ron: It shows you the value `/P Storkow` because you once logged exactly this callsign (incl. `/P`) with this value in the past. 

@int2001 We probably should omit that. I will check that out

**Comment by int2001** [comment] 2024-11-12 11:42
if we omit that, than only when logging things with dynamic location (like `/P` or `/MM` or `/AM`).
Otherwise the whole caching-logic for QRZ will break.

**Comment by HB9HIL** [comment] 2024-11-12 11:43
Yep thats the idea

**Comment by HB9HIL** [comment] 2024-11-12 12:33
@dg2ron PR is merged. Please confirm the issue fixed after update

@int2001 your turn

**Comment by dg2ron** [comment] 2024-11-12 12:44
TNX! 
cfm! All okay now. :)

**Closed** 2024-11-12 12:45 UTC
Labels: bug, wait 4 close
